#!/bin/bash
CPU_MODEL=$(awk -F': ' '/model name/{print $2; exit}' /proc/cpuinfo)
if [ "$CPU_MODEL" == "bm1688" ] || [ "$CPU_MODEL" == "cv186ah" ];then
    sudo rm /etc/systemd/system/SophonHDMIStatus.service /etc/systemd/system/multi-user.target.wants/SophonHDMIStatus.service | true
    sudo systemctl daemon-reload > /dev/null | true
    sudo systemctl enable SophonHDMI > /dev/null
    sudo systemctl restart SophonHDMI > /dev/null & 
    exit 0
fi
sudo systemctl daemon-reload > /dev/null | true
sudo systemctl restart SophonHDMIStatus > /dev/null | true
